services:
  - type: web
    name: ai-exam-backend
    env: docker
    region: oregon
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.base
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

  - type: web
    name: ai-exam-frontend
    env: docker
    region: oregon
    plan: free
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-exam-backend.onrender.com/api
