[pytest]
DJANGO_SETTINGS_MODULE = config.settings.base
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --cov=. --cov-report=term-missing --import-mode=importlib
django_find_project = true
pythonpath = . apps

