# Generated by Django 5.2.15 on 2026-07-11 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
