# Generated by Django 5.2.15 on 2026-07-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('face_absent', 'Face Absent'), ('multiple_faces', 'Multiple Faces Detected'), ('gaze_away', 'Looking Away'), ('tab_switch', 'Tab Switch'), ('window_blur', 'Window Focus Lost'), ('fullscreen_exit', 'Fullscreen Exited'), ('heartbeat', 'Normal Heartbeat')], default='heartbeat', max_length=20)),
                ('suspicion_increment', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='exams.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='SuspicionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspicion_summary', to='exams.examsession')),
            ],
        ),
    ]
