# Generated by Django 5.2.15 on 2026-07-03 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('image_answer', models.ImageField(blank=True, null=True, upload_to='handwritten_answers/')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('ai_justification', models.TextField(blank=True, null=True)),
                ('examiner_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('start_window', models.DateTimeField()),
                ('end_window', models.DateTimeField()),
                ('randomize_questions', models.BooleanField(default=True)),
                ('config_rules', models.JSONField(default=dict)),
                ('enable_webcam', models.BooleanField(default=True)),
                ('gaze_sensitivity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('max_tab_switches', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted'), ('flagged', 'Flagged')], default='in_progress', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('graded_by_ai', models.BooleanField(default=False)),
                ('finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
