# Generated by Django 5.2.15 on 2026-07-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_initial'),
        ('question_bank', '0003_uploadedpdf_question_pdf_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('config_rules', models.JSONField(blank=True, default=dict)),
                ('use_random', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='exams.examsection'),
        ),
        migrations.CreateModel(
            name='ExamSectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examsection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('section', 'question')},
            },
        ),
        migrations.AddField(
            model_name='examsection',
            name='questions',
            field=models.ManyToManyField(blank=True, through='exams.ExamSectionQuestion', to='question_bank.question'),
        ),
    ]
