# Generated by Django 5.2.15 on 2026-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examsection_examquestion_section_examsectionquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grading_mode',
            field=models.CharField(choices=[('ai_checked', 'AI Checked'), ('manual_checked', 'Manual Checked')], default='ai_checked', max_length=20),
        ),
    ]
