# Generated by Django 5.2.15 on 2026-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_grading_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='handwritten_answers/thumbnails/'),
        ),
    ]
