# Generated by Django 5.2.15 on 2026-08-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_answer_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grading_mode',
            field=models.CharField(choices=[('full_ai', 'Full AI Evaluation'), ('semi_ai', 'Semi AI (Examiner Reviews)'), ('manual', 'Manual Grading')], default='semi_ai', max_length=20),
        ),
    ]
