# Generated by Django 5.2.15 on 2026-08-11 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_exam_grading_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='cutoff_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Passing cutoff marks or score required for mass cohort assessment', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('mass', 'Mass Assessment (Cutoff & Percentile)'), ('individual', 'Individual Assessment (Single Student)')], default='mass', help_text='Mass cohort exam with cutoffs/percentiles or singular exam for a specific student', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_student',
            field=models.ForeignKey(blank=True, help_text='Specific single student if exam_type is individual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_individual_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='is_passed',
            field=models.BooleanField(blank=True, help_text='True if cleared cutoff or passed criteria', null=True),
        ),
    ]
