# Generated by Django 5.2.15 on 2026-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_cutoff_score_exam_exam_type_exam_target_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_mock',
            field=models.BooleanField(default=False, help_text='Mock practice exam open to all students'),
        ),
    ]
