# Generated by Django 5.2.15 on 2026-07-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('multi_select', 'Multi Select Checkbox'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('image_upload', 'Handwritten Image Upload')], default='mcq', max_length=20)),
                ('text', models.TextField()),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('model_answer', models.TextField(blank=True, help_text='Used for LLM grading validation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
