# Generated by Django 5.2.15 on 2026-07-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_uploadedpdf_question_pdf_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('multi_select', 'Multi Select Checkbox'), ('one_word', 'Answer in One Word'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('image_upload', 'Handwritten Image Upload')], default='mcq', max_length=20),
        ),
    ]
